--- #YAML:1.0
name:                Tk-Clock
version:             0.20
abstract:            Clock widget with analog and digital display
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Tk:                            402.000
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - H.Merijn Brand <h.m.brand@xs4all.nl>
