# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Clock
version:      0.12
version_from: Clock.pm
installdirs:  site
requires:
    Tk:                            402.000

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
