--- #YAML:1.1
name:              Tk::Clock
version:           0.23
abstract:          Clock widget with analog and digital display
license:           perl
author:              
    - H.Merijn Brand <h.merijn@xs4all.nl>
generated_by:      Author
distribution_type: module
provides:
    Tk::Clock:
        file:      Clock.pm
        version:   0.23
requires:     
    perl:          5.006
    Carp:          0
    Tk:            0
    Tk::Widget:    0
    Tk::Derived:   0
    Tk::Canvas:    0
build_requires:
    perl:          5.006
    Test::Harness: 0
    Test::More:    0
resources:
    license:       http://dev.perl.org/licenses/
meta-spec:
    version:       1.4
    url:           http://module-build.sourceforge.net/META-spec-v1.4.html
